version: '3.1'
services:
  #风铃发卡2.5版：适合个人使用
  # The Application
  php:
    image: baiyuetribe/meedu
    volumes:
      - /opt/meedu:/var/www/html
      - /opt/meedu/php.ini:/usr/local/etc/php/php.ini    
    environment:
      - "DB_PASSWORD=baiyue.one"
    networks:
        - frontend
        - backend        
    depends_on:
        - mysql
  # The Web Server
  nginx: 
    image: nginx
    volumes:
      - /opt/meedu:/var/www/html
      - /opt/meedu/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
        - frontend      
    depends_on:
        - php
  # The Database
  mysql:
    image: mysql:5.7
    volumes:
      - /opt/meedu/mysql:/var/lib/mysql
    environment:
      - "TZ=Asia/Shanghai"
      - "MYSQL_DATABASE=meedu"
      - "MYSQL_ROOT_PASSWORD=baiyue.one"
    networks:
        - backend 
  # 数据库管理
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    depends_on:
        - mysql
    environment:
        PMA_HOST: mysql
        TZ: 'Asia/Shanghai'
    networks:
        - backend
  # 数据缓存      
  redis:
      image: redis:4.0.9-alpine
      networks:
        - frontend
        - backend  
      restart: unless-stopped
        
  # 源码编辑器      
  kodexplorer:
    image: baiyuetribe/kodexplorer
    volumes:
        - /opt/meedu:/var/www/meedu      
    ports:
        - 899:80
    depends_on:
        - php  

networks:
    frontend:
    backend:  
 